# ==================================================
# services/holidays_flags.py — Flags & Category Emojis
# ==================================================
#
# Static mappings used by formatters.
#
# Rules:
# - Keys are normalized: lowercase + snake_case
# - No Cyrillic letters in keys
# - This file contains ONLY static data (no logic)
# ==================================================

# ==================================================
# Country / Region Flags
# ==================================================
COUNTRY_FLAGS = {
    # ---------------- Europe ----------------
    "albania": "🇦🇱",
    "andorra": "🇦🇩",
    "armenia": "🇦🇲",
    "austria": "🇦🇹",
    "azerbaijan": "🇦🇿",
    "belarus": "🇧🇾",
    "belgium": "🇧🇪",
    "bosnia_and_herzegovina": "🇧🇦",
    "bulgaria": "🇧🇬",
    "croatia": "🇭🇷",
    "cyprus": "🇨🇾",
    "czechia": "🇨🇿",
    "denmark": "🇩🇰",
    "estonia": "🇪🇪",
    "finland": "🇫🇮",
    "france": "🇫🇷",
    "georgia": "🇬🇪",
    "germany": "🇩🇪",
    "greece": "🇬🇷",
    "hungary": "🇭🇺",
    "iceland": "🇮🇸",
    "ireland": "🇮🇪",
    "italy": "🇮🇹",
    "kazakhstan": "🇰🇿",
    "kosovo": "🇽🇰",
    "latvia": "🇱🇻",
    "liechtenstein": "🇱🇮",
    "lithuania": "🇱🇹",
    "luxembourg": "🇱🇺",
    "malta": "🇲🇹",
    "moldova": "🇲🇩",
    "monaco": "🇲🇨",
    "montenegro": "🇲🇪",
    "netherlands": "🇳🇱",
    "north_macedonia": "🇲🇰",
    "norway": "🇳🇴",
    "poland": "🇵🇱",
    "portugal": "🇵🇹",
    "romania": "🇷🇴",
    "russia": "🇷🇺",
    "san_marino": "🇸🇲",
    "serbia": "🇷🇸",
    "slovakia": "🇸🇰",
    "slovenia": "🇸🇮",
    "spain": "🇪🇸",
    "sweden": "🇸🇪",
    "switzerland": "🇨🇭",
    "turkey": "🇹🇷",
    "ukraine": "🇺🇦",
    "uk": "🇬🇧",
    "vatican_city": "🇻🇦",

    # ---------------- Asia ----------------
    "china": "🇨🇳",
    "japan": "🇯🇵",
    "south_korea": "🇰🇷",
    "north_korea": "🇰🇵",
    "mongolia": "🇲🇳",
    "taiwan": "🇹🇼",
    "india": "🇮🇳",
    "pakistan": "🇵🇰",
    "bangladesh": "🇧🇩",
    "sri_lanka": "🇱🇰",
    "nepal": "🇳🇵",
    "bhutan": "🇧🇹",
    "maldives": "🇲🇻",
    "thailand": "🇹🇭",
    "vietnam": "🇻🇳",
    "laos": "🇱🇦",
    "cambodia": "🇰🇭",
    "myanmar": "🇲🇲",
    "malaysia": "🇲🇾",
    "singapore": "🇸🇬",
    "indonesia": "🇮🇩",
    "philippines": "🇵🇭",
    "brunei": "🇧🇳",
    "timor_leste": "🇹🇱",
    "saudi_arabia": "🇸🇦",
    "uae": "🇦🇪",
    "qatar": "🇶🇦",
    "kuwait": "🇰🇼",
    "bahrain": "🇧🇭",
    "oman": "🇴🇲",
    "iran": "🇮🇷",
    "iraq": "🇮🇶",
    "jordan": "🇯🇴",
    "lebanon": "🇱🇧",
    "israel": "🇮🇱",
    "palestine": "🇵🇸",
    "syria": "🇸🇾",
    "yemen": "🇾🇪",

    # ---------------- Africa ----------------
    "central_african_republic": "🇨🇫",
    "egypt": "🇪🇬",
    "libya": "🇱🇾",
    "tunisia": "🇹🇳",
    "algeria": "🇩🇿",
    "morocco": "🇲🇦",
    "mauritania": "🇲🇷",
    "mali": "🇲🇱",
    "niger": "🇳🇪",
    "chad": "🇹🇩",
    "sudan": "🇸🇩",
    "south_sudan": "🇸🇸",
    "eritrea": "🇪🇷",
    "ethiopia": "🇪🇹",
    "djibouti": "🇩🇯",
    "somalia": "🇸🇴",
    "kenya": "🇰🇪",
    "uganda": "🇺🇬",
    "rwanda": "🇷🇼",
    "burundi": "🇧🇮",
    "tanzania": "🇹🇿",
    "zambia": "🇿🇲",
    "zimbabwe": "🇿🇼",
    "botswana": "🇧🇼",
    "namibia": "🇳🇦",
    "south_africa": "🇿🇦",
    "angola": "🇦🇴",
    "mozambique": "🇲🇿",
    "madagascar": "🇲🇬",
    "ghana": "🇬🇭",
    "nigeria": "🇳🇬",
    "cameroon": "🇨🇲",
    "gabon": "🇬🇦",
    "congo_republic": "🇨🇬",
    "democratic_republic_of_congo": "🇨🇩",
    "ivory_coast": "🇨🇮",
    "senegal": "🇸🇳",
    "guinea": "🇬🇳",
    "guinea_bissau": "🇬🇼",
    "sierra_leone": "🇸🇱",
    "liberia": "🇱🇷",
    "benin": "🇧🇯",
    "togo": "🇹🇬",

    # ---------------- Americas ----------------
    "usa": "🇺🇸",
    "united_states": "🇺🇸",
    "canada": "🇨🇦",
    "mexico": "🇲🇽",
    "cuba": "🇨🇺",
    "jamaica": "🇯🇲",
    "haiti": "🇭🇹",
    "dominican_republic": "🇩🇴",
    "brazil": "🇧🇷",
    "argentina": "🇦🇷",
    "chile": "🇨🇱",
    "uruguay": "🇺🇾",
    "paraguay": "🇵🇾",
    "peru": "🇵🇪",
    "bolivia": "🇧🇴",
    "colombia": "🇨🇴",
    "venezuela": "🇻🇪",
    "ecuador": "🇪🇨",

    # ---------------- Oceania ----------------
    "australia": "🇦🇺",
    "new_zealand": "🇳🇿",
    "fiji": "🇫🇯",
    "samoa": "🇼🇸",
    "tonga": "🇹🇴",
    "vanuatu": "🇻🇺",
    "papua_new_guinea": "🇵🇬",

    # ---------------- Global / Religion ----------------
    "world": "🌍",
    "international": "🌐",

    "orthodox": "✝️",
    "catholic": "✝️",
    "protestant": "✝️",
    "christian": "✝️",
    "muslim": "☪️",
    "islam": "☪️",
    "jewish": "✡️",
    "judaism": "✡️",
    "buddhist": "☸️",
    "buddhism": "☸️",
    "hindu": "🕉️",
    "hinduism": "🕉️",

    # ---------------- Guild tags (pseudo-countries) ----------------
    "challenge": "⚡️",
    "complete": "🤡",
    "murloc": "🐸",
}

# ==================================================
# Category Emojis
# ==================================================
CATEGORY_EMOJIS = {
    # Guild categories
    "challenge": "⚡️",
    "accept": "💩",
    "birthday": "🥳",

    # General holidays
    "health": "🩺",
    "cultural": "🎎",
    "federal": "🏛️",
    "special_interest": "⭐",
    "cause": "🎗️",
    "food_and_beverage": "🍽️",
    "animal": "🐾",
    "appreciation": "🙏",
    "arts_and_entertainment": "🎭",
    "relationship": "❤️",
    "fun": "🎉",
    "religion": "⛪",
    "religious": "⛪",
    "activity": "⚽",
    "activities": "⚽",
    "environment": "🌱",
    "history": "📜",
    "historical": "📜",
    "technology": "💻",
    "education": "📚",
    "educational": "📚",
    "safety": "🚨",
    "fashion": "👗",
    "lifestyle": "🏡",
    "awareness": "📢",
    "civic": "🏙️",
    "children": "👶",
    "parents": "🧑‍🍼",
    "elderly": "🧓",
    "family": "👨‍👩‍👧‍👦",
    "friendship": "🤝",
    "sports": "🏅",
    "baking": "🧁",
    "cooking": "🍳",
    "food": "🍲",
    "american_food": "🍔",
    "comfort_food": "🥘",
    "chocolate": "🍫",
    "dessert": "🍰",
    "sweet_food": "🧁",
    "festivities": "🎄",
    "pop_culture": "🎤",
    "movie": "🎬",
    "movies": "🎬",
    "books": "📖",
    "dog": "🐶",
    "cat": "🐱",
    "pet": "🐾",
    "pet_health": "🐕‍🦺",
    "american": "🦅",
    "international": "🌐",
    "mental_health": "🧠",
    "conservation": "🦋",
    "wildlife": "🦁",
    "work": "💼",
    "career": "💼",
    "shopping": "🛍️",
    "brand": "🏷️",
    "beer": "🍺",
    "drinking": "🥃",
    "hobby": "🛠️",
    "pagan": "🧙‍♂️",
    "beverage": "🥤",
    "crazy": "🤪",
    "funny": "😆",
    "liquor": "🍸",
}
