# ==================================================
# services/holidays_flags.py — Holiday Emoji & Flag Maps
# ==================================================
#
# User-maintained mappings for category emojis and country flags.
#
# Layer: Services
#
# Responsibilities:
# - Encapsulate domain logic and data access
# - Keep formatting rules consistent across commands and daily jobs
# - Provide stable functions consumed by commands/daily scripts
#
# Boundaries:
# - Services may use core utilities, but should avoid importing command modules.
# - Services should not perform Telegram network calls directly (commands/daily own messaging).
#
# ==================================================
COUNTRY_FLAGS = {

    # ---------------- Europe ----------------
    "albania": "🇦🇱",
    "andorra": "🇦🇩",
    "armenia": "🇦🇲",
    "austria": "🇦🇹",
    "azerbaijan": "🇦🇿",
    "belarus": "🇧🇾",
    "belgium": "🇧🇪",
    "bosnia_and_herzegovina": "🇧🇦",
    "bulgaria": "🇧🇬",
    "croatia": "🇭🇷",
    "cyprus": "🇨🇾",
    "czechia": "🇨🇿",
    "denmark": "🇩🇰",
    "estonia": "🇪🇪",
    "finland": "🇫🇮",
    "france": "🇫🇷",
    "georgia": "🇬🇪",
    "germany": "🇩🇪",
    "greece": "🇬🇷",
    "hungary": "🇭🇺",
    "iceland": "🇮🇸",
    "ireland": "🇮🇪",
    "italy": "🇮🇹",
    "kazakhstan": "🇰🇿",
    "kosovo": "🇽🇰",
    "latvia": "🇱🇻",
    "liechtenstein": "🇱🇮",
    "lithuania": "🇱🇹",
    "luxembourg": "🇱🇺",
    "malta": "🇲🇹",
    "moldova": "🇲🇩",
    "monaco": "🇲🇨",
    "montenegro": "🇲🇪",
    "netherlands": "🇳🇱",
    "north_macedonia": "🇲🇰",
    "norway": "🇳🇴",
    "poland": "🇵🇱",
    "portugal": "🇵🇹",
    "romania": "🇷🇴",
    "russia": "🇷🇺",
    "san_marino": "🇸🇲",
    "serbia": "🇷🇸",
    "slovakia": "🇸🇰",
    "slovenia": "🇸🇮",
    "spain": "🇪🇸",
    "sweden": "🇸🇪",
    "switzerland": "🇨🇭",
    "turkey": "🇹🇷",
    "ukraine": "🇺🇦",
    "uk": "🇬🇧",
    "vatican_city": "🇻🇦",

    # ---------------- Asia ----------------
    "china": "🇨🇳",
    "japan": "🇯🇵",
    "south_korea": "🇰🇷",
    "north_korea": "🇰🇵",
    "mongolia": "🇲🇳",
    "taiwan": "🇹🇼",
    "india": "🇮🇳",
    "pakistan": "🇵🇰",
    "bangladesh": "🇧🇩",
    "sri_lanka": "🇱🇰",
    "nepal": "🇳🇵",
    "bhutan": "🇧🇹",
    "maldives": "🇲🇻",
    "thailand": "🇹🇭",
    "vietnam": "🇻🇳",
    "laos": "🇱🇦",
    "cambodia": "🇰🇭",
    "myanmar": "🇲🇲",
    "malaysia": "🇲🇾",
    "singapore": "🇸🇬",
    "indonesia": "🇮🇩",
    "philippines": "🇵🇭",
    "brunei": "🇧🇳",
    "timor_leste": "🇹🇱",
    "saudi_arabia": "🇸🇦",
    "uae": "🇦🇪",
    "qatar": "🇶🇦",
    "kuwait": "🇰🇼",
    "bahrain": "🇧🇭",
    "oman": "🇴🇲",
    "iran": "🇮🇷",
    "iraq": "🇮🇶",
    "jordan": "🇯🇴",
    "lebanon": "🇱🇧",
    "israel": "🇮🇱",
    "palestine": "🇵🇸",
    "syria": "🇸🇾",
    "yemen": "🇾🇪",

    # ---------------- Africa ----------------
    "central_african_republic": "🇨🇫",
    "egypt": "🇪🇬",
    "libya": "🇱🇾",
    "tunisia": "🇹🇳",
    "algeria": "🇩🇿",
    "morocco": "🇲🇦",
    "mauritania": "🇲🇷",
    "mali": "🇲🇱",
    "niger": "🇳🇪",
    "chad": "🇹🇩",
    "sudan": "🇸🇩",
    "south_sudan": "🇸🇸",
    "eritrea": "🇪🇷",
    "ethiopia": "🇪🇹",
    "djibouti": "🇩🇯",
    "somalia": "🇸🇴",
    "kenya": "🇰🇪",
    "uganda": "🇺🇬",
    "rwanda": "🇷🇼",
    "burundi": "🇧🇮",
    "tanzania": "🇹🇿",
    "zambia": "🇿🇲",
    "zimbabwe": "🇿🇼",
    "botswana": "🇧🇼",
    "namibia": "🇳🇦",
    "south_africa": "🇿🇦",
    "angola": "🇦🇴",
    "mozambique": "🇲🇿",
    "madagascar": "🇲🇬",
    "ghana": "🇬🇭",
    "nigeria": "🇳🇬",
    "cameroon": "🇨🇲",
    "gabon": "🇬🇦",
    "congo_republic": "🇨🇬",
    "democratic_republic_of_congo": "🇨🇩",
    "ivory_coast": "🇨🇮",
    "senegal": "🇸🇳",
    "guinea": "🇬🇳",
    "guinea_bissau": "🇬🇼",
    "sierra_leone": "🇸🇱",
    "liberia": "🇱🇷",
    "benin": "🇧🇯",
    "togo": "🇹🇬",

    # ---------------- Americas ----------------
    "usa": "🇺🇸",
    "canada": "🇨🇦",
    "mexico": "🇲🇽",
    "cuba": "🇨🇺",
    "jamaica": "🇯🇲",
    "haiti": "🇭🇹",
    "dominican_republic": "🇩🇴",
    "brazil": "🇧🇷",
    "argentina": "🇦🇷",
    "chile": "🇨🇱",
    "uruguay": "🇺🇾",
    "paraguay": "🇵🇾",
    "peru": "🇵🇪",
    "bolivia": "🇧🇴",
    "colombia": "🇨🇴",
    "venezuela": "🇻🇪",
    "ecuador": "🇪🇨",

    # ---------------- Oceania ----------------
    "australia": "🇦🇺",
    "new_zealand": "🇳🇿",
    "fiji": "🇫🇯",
    "samoa": "🇼🇸",
    "tonga": "🇹🇴",
    "vanuatu": "🇻🇺",
    "papua_new_guinea": "🇵🇬",

    # ---------------- Global / Religion ----------------
    "world": "🌍",
    "international": "🌐",
    "orthodox": "✝️",
    "catholic": "✝️",
    "protestant": "✝️",
    "christian": "✝️",
    "muslim": "☪️",
    "islam": "☪️",
    "jewish": "✡️",
    "judaism": "✡️",
    "buddhist": "☸️",
    "buddhism": "☸️",
    "hindu": "🕉️",
    "hinduism": "🕉️",

# birthday
    "Сhallenge": "⚡️",
    "Сomplete": "🤡",
    "Murloc": "🐸",
}

# ==================================================
# Holiday Category Emojis
# ==================================================
#
# Maps holiday category names to emojis.
#
# NOTE:
# - Category names must match source data exactly.
# - Multiple aliases are intentionally supported
#   (e.g. "Religion" / "Religious").
#

CATEGORY_EMOJIS = {
    "Health": "🩺",
    "Cultural": "🎎",
    "Federal": "🏛️",
    "Special Interest": "⭐",
    "Cause": "🎗️",
    "Food & Beverage": "🍽️",
    "Animal": "🐾",
    "Appreciation": "🙏",
    "Arts & Entertainment": "🎭",
    "Relationship": "❤️",
    "Fun": "🎉",
    "Religion": "⛪",
    "Religious": "⛪",
    "Activity": "⚽",
    "Activities": "⚽",
    "Environment": "🌱",
    "History": "📜",
    "Historical": "📜",
    "Technology": "💻",
    "Education": "📚",
    "Educational": "📚",
    "Safety": "🚨",
    "Fashion": "👗",
    "Lifestyle": "🏡",
    "Awareness": "📢",
    "Civic": "🏙️",
    "Children": "👶",
    "Parents": "🧑‍🍼",
    "Elderly": "🧓",
    "Family": "👨‍👩‍👧‍👦",
    "Friendship": "🤝",
    "Sports": "🏅",
    "Baking": "🧁",
    "Cooking": "🍳",
    "Food": "🍲",
    "American food": "🍔",
    "Comfort Food": "🥘",
    "Chocolate": "🍫",
    "Dessert": "🍰",
    "Sweet Food": "🧁",
    "Festivities": "🎄",
    "Pop Culture": "🎤",
    "Movie": "🎬",
    "Movies": "🎬",
    "Books": "📖",
    "Dog": "🐶",
    "Cat": "🐱",
    "Pet": "🐾",
    "Pet Health": "🐕‍🦺",
    "American": "🦅",
    "International": "🌐",
    "Mental Health": "🧠",
    "Conservation": "🦋",
    "Wildlife": "🦁",
    "Work": "💼",
    "Career": "💼",
    "Shopping": "🛍️",
    "Brand": "🏷️",
    "Beer": "🍺",
    "Drinking": "🥃",
    "Hobby": "🛠️",
    "Pagan": "🧙‍♂️",
    "Catholic": "✝️",
    "Christian": "✝️",
    "Beverage": "🥤",
    "Crazy": "🤪",
    "Funny": "😆",
    "Liquor": "🍸",
# birthday
    "Сhallenge": "😱",
    "Accept": "💩",
    "Birthday": "🥳",
}