# ==================================================
# services/holidays_flags.py — Flags & Category Emojis
# ==================================================
#
# Static mappings used by the formatting layer.
# Keep this file DATA-ONLY (no Telegram calls, no side effects).
#
# IMPORTANT:
# - Keys must be normalized: lowercase, snake_case where applicable.
# - If your source data contains Title Case (e.g. "Cultural"),
#   normalize it in the formatter (recommended) rather than duplicating keys here.
# ==================================================


COUNTRY_FLAGS = {'albania': '🇦🇱',
 'algeria': '🇩🇿',
 'andorra': '🇦🇩',
 'angola': '🇦🇴',
 'argentina': '🇦🇷',
 'armenia': '🇦🇲',
 'australia': '🇦🇺',
 'austria': '🇦🇹',
 'azerbaijan': '🇦🇿',
 'bahrain': '🇧🇭',
 'bangladesh': '🇧🇩',
 'belarus': '🇧🇾',
 'belgium': '🇧🇪',
 'benin': '🇧🇯',
 'bhutan': '🇧🇹',
 'bolivia': '🇧🇴',
 'bosnia_and_herzegovina': '🇧🇦',
 'botswana': '🇧🇼',
 'brazil': '🇧🇷',
 'brunei': '🇧🇳',
 'buddhism': '☸️',
 'buddhist': '☸️',
 'bulgaria': '🇧🇬',
 'burundi': '🇧🇮',
 'cambodia': '🇰🇭',
 'cameroon': '🇨🇲',
 'canada': '🇨🇦',
 'catholic': '✝️',
 'central_african_republic': '🇨🇫',
 'chad': '🇹🇩',
 'challenge': '⚡️',
 'chile': '🇨🇱',
 'china': '🇨🇳',
 'christian': '✝️',
 'colombia': '🇨🇴',
 'complete': '🤡',
 'congo_republic': '🇨🇬',
 'croatia': '🇭🇷',
 'cuba': '🇨🇺',
 'cyprus': '🇨🇾',
 'czechia': '🇨🇿',
 'democratic_republic_of_congo': '🇨🇩',
 'denmark': '🇩🇰',
 'djibouti': '🇩🇯',
 'dominican_republic': '🇩🇴',
 'ecuador': '🇪🇨',
 'egypt': '🇪🇬',
 'eritrea': '🇪🇷',
 'estonia': '🇪🇪',
 'ethiopia': '🇪🇹',
 'fiji': '🇫🇯',
 'finland': '🇫🇮',
 'france': '🇫🇷',
 'gabon': '🇬🇦',
 'georgia': '🇬🇪',
 'germany': '🇩🇪',
 'ghana': '🇬🇭',
 'greece': '🇬🇷',
 'guinea': '🇬🇳',
 'guinea_bissau': '🇬🇼',
 'haiti': '🇭🇹',
 'hindu': '🕉️',
 'hinduism': '🕉️',
 'hungary': '🇭🇺',
 'iceland': '🇮🇸',
 'india': '🇮🇳',
 'indonesia': '🇮🇩',
 'international': '🌐',
 'iran': '🇮🇷',
 'iraq': '🇮🇶',
 'ireland': '🇮🇪',
 'islam': '☪️',
 'israel': '🇮🇱',
 'italy': '🇮🇹',
 'ivory_coast': '🇨🇮',
 'jamaica': '🇯🇲',
 'japan': '🇯🇵',
 'jewish': '✡️',
 'jordan': '🇯🇴',
 'judaism': '✡️',
 'kazakhstan': '🇰🇿',
 'kenya': '🇰🇪',
 'kosovo': '🇽🇰',
 'kuwait': '🇰🇼',
 'laos': '🇱🇦',
 'latvia': '🇱🇻',
 'lebanon': '🇱🇧',
 'liberia': '🇱🇷',
 'libya': '🇱🇾',
 'liechtenstein': '🇱🇮',
 'lithuania': '🇱🇹',
 'luxembourg': '🇱🇺',
 'madagascar': '🇲🇬',
 'malaysia': '🇲🇾',
 'maldives': '🇲🇻',
 'mali': '🇲🇱',
 'malta': '🇲🇹',
 'mauritania': '🇲🇷',
 'mexico': '🇲🇽',
 'moldova': '🇲🇩',
 'monaco': '🇲🇨',
 'mongolia': '🇲🇳',
 'montenegro': '🇲🇪',
 'morocco': '🇲🇦',
 'mozambique': '🇲🇿',
 'murloc': '🐸',
 'muslim': '☪️',
 'myanmar': '🇲🇲',
 'namibia': '🇳🇦',
 'nepal': '🇳🇵',
 'netherlands': '🇳🇱',
 'new_zealand': '🇳🇿',
 'niger': '🇳🇪',
 'nigeria': '🇳🇬',
 'north_korea': '🇰🇵',
 'north_macedonia': '🇲🇰',
 'norway': '🇳🇴',
 'oman': '🇴🇲',
 'orthodox': '✝️',
 'pakistan': '🇵🇰',
 'palestine': '🇵🇸',
 'papua_new_guinea': '🇵🇬',
 'paraguay': '🇵🇾',
 'peru': '🇵🇪',
 'philippines': '🇵🇭',
 'poland': '🇵🇱',
 'portugal': '🇵🇹',
 'protestant': '✝️',
 'qatar': '🇶🇦',
 'romania': '🇷🇴',
 'russia': '🇷🇺',
 'rwanda': '🇷🇼',
 'samoa': '🇼🇸',
 'san_marino': '🇸🇲',
 'saudi_arabia': '🇸🇦',
 'senegal': '🇸🇳',
 'serbia': '🇷🇸',
 'sierra_leone': '🇸🇱',
 'singapore': '🇸🇬',
 'slovakia': '🇸🇰',
 'slovenia': '🇸🇮',
 'somalia': '🇸🇴',
 'south_africa': '🇿🇦',
 'south_korea': '🇰🇷',
 'south_sudan': '🇸🇸',
 'spain': '🇪🇸',
 'sri_lanka': '🇱🇰',
 'sudan': '🇸🇩',
 'sweden': '🇸🇪',
 'switzerland': '🇨🇭',
 'syria': '🇸🇾',
 'taiwan': '🇹🇼',
 'tanzania': '🇹🇿',
 'thailand': '🇹🇭',
 'timor_leste': '🇹🇱',
 'togo': '🇹🇬',
 'tonga': '🇹🇴',
 'tunisia': '🇹🇳',
 'turkey': '🇹🇷',
 'uae': '🇦🇪',
 'uganda': '🇺🇬',
 'uk': '🇬🇧',
 'ukraine': '🇺🇦',
 'uruguay': '🇺🇾',
 'usa': '🇺🇸',
 'vanuatu': '🇻🇺',
 'vatican_city': '🇻🇦',
 'venezuela': '🇻🇪',
 'vietnam': '🇻🇳',
 'world': '🌍',
 'yemen': '🇾🇪',
 'zambia': '🇿🇲',
 'zimbabwe': '🇿🇼'}


CATEGORY_EMOJIS = {'accept': '💩',
 'activities': '⚽',
 'activity': '⚽',
 'american': '🦅',
 'american food': '🍔',
 'animal': '🐾',
 'appreciation': '🙏',
 'arts & entertainment': '🎭',
 'awareness': '📢',
 'baking': '🧁',
 'beer': '🍺',
 'beverage': '🥤',
 'birthday': '🥳',
 'books': '📖',
 'brand': '🏷️',
 'career': '💼',
 'cat': '🐱',
 'catholic': '✝️',
 'cause': '🎗️',
 'challenge': '⚡️',
 'children': '👶',
 'chocolate': '🍫',
 'christian': '✝️',
 'civic': '🏙️',
 'comfort food': '🥘',
 'complete': '🤡',
 'conservation': '🦋',
 'cooking': '🍳',
 'crazy': '🤪',
 'cultural': '🎎',
 'dessert': '🍰',
 'dog': '🐶',
 'drinking': '🥃',
 'education': '📚',
 'educational': '📚',
 'elderly': '🧓',
 'environment': '🌱',
 'family': '👨\u200d👩\u200d👧\u200d👦',
 'fashion': '👗',
 'federal': '🏛️',
 'festivities': '🎄',
 'food': '🍲',
 'food & beverage': '🍽️',
 'friendship': '🤝',
 'fun': '🎉',
 'funny': '😆',
 'health': '🩺',
 'historical': '📜',
 'history': '📜',
 'hobby': '🛠️',
 'international': '🌐',
 'lifestyle': '🏡',
 'liquor': '🍸',
 'mental health': '🧠',
 'movie': '🎬',
 'movies': '🎬',
 'murloc': '🐸',
 'pagan': '🧙\u200d♂️',
 'parents': '🧑\u200d🍼',
 'pet': '🐾',
 'pet health': '🐕\u200d🦺',
 'pop culture': '🎤',
 'relationship': '❤️',
 'religion': '⛪',
 'religious': '⛪',
 'safety': '🚨',
 'shopping': '🛍️',
 'special interest': '⭐',
 'sports': '🏅',
 'sweet food': '🧁',
 'technology': '💻',
 'wildlife': '🦁',
 'work': '💼'}

# ==================================================
# UI / Formatting Emojis
# ==================================================
#
# Small set of non-holiday emojis used by formatters.
# Kept here so the formatting layer can stay data-driven.
#

UI_EMOJIS = {
    "guild_events_header": "📅",
    "birthdays_header": "🎂",
    "date_range": "🗓️",
}
